# Generated by Django 4.1.7 on 2024-04-08 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 8, 11, 34, 50, 550489))),
            ],
        ),
    ]
