# Generated by Django 4.1.7 on 2024-04-08 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentattendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollno',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 8, 11, 58, 26, 374177)),
        ),
    ]
